### ISSUE TITLE
Error in inference: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by Jiltseb** [Sreyan88/GAMA#3] opened 2024-07-01 12:48 UTC
For the inference, I am getting the following error in the generate() function:

```
Traceback (most recent call last):
  File "/home/jilt/workspace/experiments/GAMA/gama_inf.py", line 294, in <module>
    fire.Fire(main)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/jilt/workspace/experiments/GAMA/gama_inf.py", line 270, in main
    generation_output = model.generate(
  File "/home/jilt/workspace/experiments/GAMA/peft-main/src/peft/peft_model.py", line 539, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jilt/workspace/experiments/GAMA/hf-dev-train/transformers-main/src/transformers/generation/utils.py", line 1472, in generate
    return self.sample(
  File "/home/jilt/workspace/experiments/GAMA/hf-dev-train/transformers-main/src/transformers/generation/utils.py", line 2504, in sample
    outputs = self(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jilt/workspace/experiments/GAMA/hf-dev-train/transformers-main/src/transformers/models/llama/modeling_llama.py", line 1276, in forward
    outputs = self.model(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jilt/workspace/experiments/GAMA/hf-dev-train/transformers-main/src/transformers/models/llama/modeling_llama.py", line 1158, in forward
    layer_outputs = decoder_layer(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jilt/workspace/experiments/GAMA/hf-dev-train/transformers-main/src/transformers/models/llama/modeling_llama.py", line 429, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jilt/workspace/experiments/GAMA/hf-dev-train/transformers-main/src/transformers/models/llama/modeling_llama.py", line 330, in forward
    cos, sin = self.rotary_emb(value_states, seq_len=kv_seq_len)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/hooks.py", line 290, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/utils/operations.py", line 151, in send_to_device
    return honor_type(
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/utils/operations.py", line 83, in honor_type
    return type(obj)(generator)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/utils/operations.py", line 152, in <genexpr>
    tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
  File "/home/jilt/anaconda3/envs/gama_n/lib/python3.10/site-packages/accelerate/utils/operations.py", line 167, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```
I also see that the variable `msg` is then used: `    msg = model.load_state_dict(state_dict, strict=False)`

Any help is greatly appreciated!

**Comment by Sreyan88** [comment] 2024-07-01 18:54
Thank You for the question! We are looking into it!

**Comment by sonalkum** [comment] 2024-07-01 19:41
Hi @Jiltseb, we are unable to reproduce this issue. Can you please confirm which checkpoint are you using and have you changed the base_model path in the file? It will also be helpful if you share a snapshot of how are you loading the checkpoint. Thanks!!

**Comment by Jiltseb** [comment] 2024-07-01 21:00
Hi @sonalkum and @Sreyan88 
I am using the basemodel `Llama-2-7b-chat-hf-qformer` provided with safetensors downloaded from HF repo as it was not available. As `eval_mdl_path`, I am using `fs/gamma-projects/audio/ltu/new_data_no_aggr/stage4_all_mix/checkpoint-23400/pytorch_model.bin` model (Not sure which one to use for inference actually).


The loading part is below:

```
root_dir = "/nas/jilt/datasets/audio_description"

def main(
    base_model: str = os.path.join(root_dir,"GAMA/Llama-2-7b-chat-hf-qformer"),
    
    prompt_template: str = "alpaca_short",  # The prompt template to use, will default to alpaca.
):
    base_model = base_model or os.environ.get("BASE_MODEL", "")
    assert (
        base_model
    ), "Please specify a --base_model, e.g. --base_model='huggyllama/llama-7b'"

    prompter = Prompter(prompt_template)
    tokenizer = LlamaTokenizer.from_pretrained(base_model)

    # model = LlamaForCausalLM.from_pretrained(base_model, device_map="auto")
    model = LlamaForCausalLM.from_pretrained(base_model, device_map="auto")#, torch_dtype=torch.bfloat16)


    config = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.0,
        bias="none",
        task_type="CAUSAL_LM",
    )

    model = get_peft_model(model, config)
    temp, top_p, top_k = 0.1, 0.95, 500
    # change it to your model path
    #/fs/nexus-projects/brain_project/acl_sk_24/GAMA//exp/stage4_all_mix/checkpoint-18000/
    #/fs/nexus-projects/brain_project/acl_sk_24/GAMA//exp/stage5_all_mix/checkpoint-700/pytorch_model.bin
    
    #see this
    eval_mdl_path = os.path.join(root_dir, 'GAMA/fs/gamma-projects/audio/ltu/new_data_no_aggr/stage4_all_mix/checkpoint-23400/pytorch_model.bin')
```
`model` and `input_ids` device are the same (cuda:0)
Update: I pulled the latest one but the error still appears. Is there any limitation on the type of GPU? I am using 24G NVIDIA TITAN RTX

**Comment by sonalkum** [comment] 2024-07-01 22:04
Hi @Jiltseb, we are still not able to reproduce the issue. Can you try changing device_map="auto" to device_map="cpu"? Also we checked the log and it is taking close to 27G of VRAM, so GPU might be an issue. We only have A6000 machines, so it might be difficult for us to check on the mentioned GPU.

**Comment by Jiltseb** [comment] 2024-07-02 11:57
Thanks, I tried it on A6000 and it works. Has something to do with the older machines/lack of memory.

Trying CPU loading for the base model:
`ValueError: If passing a string for `device_map`, please choose 'auto', 'balanced', 'balanced_low_0' or 'sequential'.`

I will stick with A6000 FTB.

Also its not quite clear which model performs the the best given the checkpoints. Do you have benchmarking numbers to compare them (stage 4&5 diff epochs)?

**Comment by Sreyan88** [comment] 2024-07-02 16:55
Thank You! Closing the issue. Please feel free to open if you face any more issues!

Thank You!

**Closed as completed by Sreyan88** 2024-07-02 16:55 UTC

**Comment by Sreyan88** [comment] 2024-07-02 18:37
Hi @Jiltseb ,

Sorry missed the later part of your message. Stage 4 is GAMA and stage 5 is GAMA-IT (difference can be found from our paper, GAMA-IT is fine-tuned on Compa-R with stage 4 checkpoints)

Additionally, you will find some files with `_epoch2` on some checkpoints. From our paper; Stage 4 is trained on just 1 epoch but we did an additional experiment where we trained it for 2 epochs. Results on paper are 1 epoch results. The 2 epoch results have still not been benchmarked and its in our to-do list. Correspondingly,  `_epoch2`  for stage 5 is GAMA-IT fine-tuned on 2 epoch version of GAMA (stage 4).

**Comment by Jiltseb** [comment] 2024-07-02 20:48
Awesome! Thanks.

**Comment by PrometheusUA** [comment] 2025-04-20 08:52
For all those who are stuck on this problem and have a GPU with less than 27 GB VRAM, you can try inferencing and training in float16 or bfloat16 mode. The results can be worse than for the original model, and are not benchmarked, but you can at least manually check everything. 

On my machine, the model used 14.5 GB of VRAM with bfloat16 inference. I just made two changes to `gama_inf_single_audio.py`:
```python
model = LlamaForCausalLM.from_pretrained(base_model, device_map="auto", torch_dtype=torch.bfloat16)
```

```python
def load_audio(filename):
    ...
    return fbank.to(torch.bfloat16), audio_info
```
